### ISSUE TITLE
Debug Console: Hyperlink to error line

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#10]
![image](https://user-images.githubusercontent.com/1964198/84085499-52b02a00-a9ab-11ea-8630-6b14cbeae48d.png)

Clicking on hyperlink moves cursor to line 1.  Is possible to instead jump to error line i.e. Line 142 in example above?

**Comment by zero-plusplus** [comment]
Is possible.

This is because the format that vscode recognizes as a link is different, so it can be realized by processing the path as such.

This issue will be fixed in the next version upgrade.

**Comment by SAbboushi** [comment]
Excellent!
