### ISSUE TITLE
[v2] Breakpoints do not work when Fat Arrow is assigned to a variable

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#105]
It does not work when a breakpoint is set on a line where a variable is assigned a function object or closure using Fat Arrow as shown below.
I checked and it seems that `a122` already has this bug.
```ahk
func := () => "func"
closure := () => func
```

However, if call it as follows, the breakpoint will work correctly. Therefore, this may be a specification or bug in the AutoHotkey debugger.
```ahk
%func%()
```

I need to find out if this bug is due to a specification or an extension.

**Comment by zero-plusplus** [comment]
When I checked with SciTE4AutoHotkey, the behavior was the same, so I'm going to assume that this is the current specification  or bug of AutoHotkey and close this issue.

**Comment by Lexikos** [comment]
This is still listed as a known issue on the wiki, but it was fixed before the v2.0.0 release (AutoHotkey/AutoHotkey@95d36a3).

**Comment by zero-plusplus** [comment]
Thank you for your report.
I had forgotten its page existed when I noticed the fix.

The wiki has just been updated. It can be found below link.
* https://github.com/zero-plusplus/vscode-autohotkey-debug/wiki/Known-issues
