### ISSUE TITLE
Add `@Debug-Log` directive

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#122]
Supports output and writing to files depending on the level.

#### example:
```
; @Debug-Log => Simple Log
; @Debug-Log:Warn => Warn Level Log
```

I need to think about the configuration structure. For that I need to learn about log output in general.

The following is a draft of the configuration that will be needed.
#### - `logfile`: *string*
Log file settings. Need to be able to set the name using variables like `{YYYY}-{MM}-{dd}.log`.

#### - `levelDefinition`: *string[]*
Definition of level. Defaults to `[ "INFO", "WARN", "ERROR", "FATAL" ]`.

#### - `outputLevel`: *string* | *string[]* | *{ [key: string]: boolean }*
The level to output. If specified string, outputs all levels below the specified level.  Otherwise, only the specified level will be output.

The following means the same thing:
```
"WARN"
[ "INFO", "WARN" ]
{ "INFO": true,  "WARN": true }
```

#### - `format`: *string*
Output format. e.g. `{YYYY}-{MM}-{dd} {hh}:{mm}:{ss} {level} {message}`

**Comment by SAbboushi** [comment]
I am envious of the education you are getting from your research and testing.

**Comment by zero-plusplus** [comment]
I was trying to think of a way to solve this [issue](#121), but it inevitably depends on the debugger adapter and is difficult to solve with a library on the AutoHotkey side.

This directive may be able to solve the above issue.

So I came up with a solution to the issue of this directive.
1. add an attribute to set the output format (JSON, CSON, etc.) and indentation
2. add an attribute to enable logging only for specific files

This will solve the issue for now.

After that, I just need to create a meta-variable that provides a way to output `Local`, `Global`, or a custom category, and all the issues will be solved.

If it can be implemented, reopen this issue and add it in the next version.

**Comment by zero-plusplus** [comment]
I didn't check it enough. The link has been corrected.

**Comment by zero-plusplus** [comment]
Hmm, I still think it's wrong to try to output objects in the log. And it's also strange to treat logging as a debug-only feature.

Although I cannot meet the requirement of writing to a file, I can solve half of this issue by adding a meta-variable that will output all variables contained in the category.

For example.
```ahk
; @Debug-Output => {{Local}}
; @Debug-Output => {{Global}}
; @Debug-Output => {{Category[1]}}
```
