### ISSUE TITLE
[v2] Debugging is forced to terminate with error code 3221225477

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#136]
In v2, this occurred when stepping through a catch statement when an error object was stored in a variable.

However, if I place a breakpoint on the statement within the catch statement and try again, this issue does not occur.

Also, strangely enough, I checked the debugger itself by debugging it, but this issue did not occur.

I tried with another script, but could not reproduce the issue , so it seems that the catch statement is not the cause of the issue.

**Comment by Lexikos** [comment]
I have determined that the crash occurs if the debugger causes a property to be invoked while halted at (not within) the `catch`. The debugger clears the exception after evaluating the property, under the assumption that it was thrown by the property.

Lexikos/AutoHotkey_L@082ee7ba will avoid the issue by causing `catch` to be skipped over like `else`. If you want to work around it for current and past versions, you could do something similar (if execution breaks at `catch`, immediately step).

**Comment by zero-plusplus** [comment]
Thanks for the fix.

I will try to implement a workaround given by you to support the current and past versions.

**Comment by zero-plusplus** [comment]
To avoid code hype, I did not add any workarounds.

This is because v2 is still under development and we decided that it is not necessary.
