### ISSUE TITLE
Link is wrong to report issues

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#14]
Extension "Details" tab after  installing extension:

Shows link to [https://github.com/zero-plusplus/vscode-autohotkey-debug/blob/master/https:github.com/zero-plusplus/vscode-autohotkey-debug/issues](https://github.com/zero-plusplus/vscode-autohotkey-debug/blob/master/https:github.com/zero-plusplus/vscode-autohotkey-debug/issues)

**Comment by zero-plusplus** [comment]
Thank you for reporting. It was fixed in the develop branch. This issue will be fixed in the next update.
