### ISSUE TITLE
Planning the 1.10.0

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#144]
**Not everything written here will be implemented in the next version.**
- [x] Add: #75
  - [x] Implement
  - [x] Document
  - [x] Test
- [x] Add: #88
  - [x] Implement
  - [x] Document
  - [x] Test
- [x] Add: #142 
  - [x] useAnnounce
    ```
    useAnnounce: boolean | "error" | "detail" = true;
    ```
    - [x] Implement
    - [x] Document
    - [x] Test
  - [x] useOutputDebug
    - [x] Consider the option for OutputDebug. The following is a draft.
      ```
      useOutputDebug: {
        category: "stdout" | "stderr" | "console";
        useTrailingLinebreak: boolean;
      }
      ```
    - [x] Implement
    - [x] Document
    - [x] Test
  
- [x] Add #147
  - [x] Implement
  - [x] Document
  - [x] Test
- [x] Add: #148 
  - [x] Implement
  - [x] Document
  - [x] Test
- [x] Add: #150
  - [x] Implement
  - [x] Document
  - [x] Test
- [x] Add: #151
  - [x] Implement
  - [x] Document
  - [x] Test
- [x] Add: #154
  - [x] Implement
  - [x] Document
  - [x] Test
- [x] Add: #162
  - [x] Implement
  - [x] Document
  - [x] Test
- [x] Add: #173
  - [x] Implement
  - [x] Document
  - [x] Test
- [x] Change: #157
  - [x] Implement
  - [x] Document
  - [x] Test
- [x] Change: #161
  - [x] Implement
  - [x] Document
  - [x] Test
- [x] Change: #165
  - [x] Implement
  - [x] ~~Document~~
  - [x] Test
- [x] Change: #176
  - [x] Implement
  - [x] Document
  - [x] Test
- [x] Fix: #134
- [x] Fix: #146
- [x] Fix: Improve breakpoint processing
- [x] Fix: #149
- [x] Fix: #158
- [x] Fix: #159
- [x] Fix: #160
- [x] Fix: #163
- [x] Fix: #164
- [x] Fix: #167
- [x] Fix: #168
- [x] Fix: #169
- [x] Fix: #171
- [x] Fix: #177
- [x] Fix: #178

- [x] Adjustment tasks for the current development version
  - [x] Display suggestions as `base` instead of `<base>`
  - [x] The `instance.<base>. <base>` will be modified in the next AutoHotkey-v1, so change to a simple process. The workaround code will remain to work in the current or previous versions
  - [x] Fix the issue of incorrect watch expression in AutoExec section.
- [x] Area of influence
  - [x] Data inspection
  - [x] Watch expression
  - [x] Call stack
  - [x] Loaded scripts
  - [x] Conditional breakpoint
  - [x] Hit count breakpoint
  - [x] Log point
  - [x] Intellisense
  - [x] PerfTips
  - [x] Debug console

- [x] Recheck the documentation
- [x] Change bundling process from webpack to esbuild
- [x] Final check using Windows SandBox.

**Comment by pepeu93** [comment]
Hello, when this version will be available?

**Comment by zero-plusplus** [comment]
It will be released in December.
Since this update is very large, it is taking a long time to check for bugs and adjust the specifications.

You can check the latest work [here](https://github.com/zero-plusplus/vscode-autohotkey-debug/commits/release).

**Comment by zero-plusplus** [comment]
I am pleased to announce the release of `1.10.0`.

Since I was able to implement most of the technically implementable drafts and requests
There will be no further feature additions for a while.

Thank you for waiting so long.

**Comment by SAbboushi** [comment]
Very good news!  Thank you!

**Comment by zero-plusplus** [comment]
I'm glad you like it.

I' m going to keep fixing bugs, so if you find any, please let me know.
