### ISSUE TITLE
;@Debug-Output not working in #Include

### ISSUE THREAD

**Issue by Lexikos** [zero-plusplus/vscode-autohotkey-debug#159]
I am unable to get `; @Debug-Output => message` to work in any #Include file with v1.9.0.

For example, with file 1:

    #Include C:\full path\file 2.ahk
    ; @Debug-Output => message 1
    a := 1

and file 2:

    ; @Debug-Output => message 2
    a := 2

I see only "message 1". Originally I was using a relative path with v2, but noticed #134, so I have tested with both full and relative paths, with and without A_ScriptDir or A_LineFile\.., and both v1 and v2.

Adding a logpoint via the GUI does work in all files.

**Comment by zero-plusplus** [comment]
@Lexikos
I released `1.10.0` which includes a fix for this issue.

Thanks for reporting this and other issues.
