### ISSUE TITLE
[Documentation] "Advanced breakpoints" link is broken

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#16]
useAdvancedBreakpoint: Unlock conditional breakpoints, etc. See _Advanced breakpoints_ for details

![image](https://user-images.githubusercontent.com/1964198/85746880-6b6b5000-b6cc-11ea-88a2-3103c3b28854.png)

**Comment by zero-plusplus** [comment]
Thank you for reporting.

I didn't notice it in the Markdown preview of vscode as the link worked fine.
