### ISSUE TITLE
[enhancement] Setting for port range to avoid prompting for port#

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#17]
I would benefit from a setting that would allow me to define a port range to automatically assign when debugging multiple scripts without prompting each time.

I know you added a "port" setting that I can customize in launch.json, but I often debug at the same time multiple scripts within the same vscode workspace/ same folder, so the port setting does not solve my problem.

My idea is something like:
`"PortRange": [ 9003-9013 ]`

And if port range is used up, then prompt for next port e.g. "9014" in my example setting above.

**Comment by zero-plusplus** [comment]
It's a very good idea that the user can declare the port to use in advance.

It will be implemented in the next version.

**Comment by zero-plusplus** [comment]
The `port` has been extended to accept strings like `"start-last"`.
`start` and `last` are numbers. You also need to set it so that `start <last`.
For example, `"9000-9013"`.

The next version will be released soon.

**Comment by SAbboushi** [comment]
EXCELLENT!  Thank you!

Also, I think maybe you did not get my private messages from autohotkey forum?

**Comment by zero-plusplus** [comment]
Thanks for introducing to this extension.
I was aware of the private message, but I can't reply to it, probably due to limited functionality.

I'll give you my email address, and I've added it to my Github profile.
`contact@zero-plusplus.com`
