### ISSUE TITLE
Failed to display COM information 

### ISSUE THREAD

**Issue by thqby** [zero-plusplus/vscode-autohotkey-debug#188]
![image](https://user-images.githubusercontent.com/28240311/149665330-015c982b-9e81-467f-922c-4a0513c9e8ac.png)

**Comment by zero-plusplus** [comment]
I was able to display COM information with the following code.
```ahk
comobj := ComObject("InternetExplorer.Application")
```

Please tell me the code that fails.

**Comment by thqby** [comment]
```
NumPut("int64", 0x20400, "int64", 0x46000000000000c0, IDispatch := Buffer(16))
lresult := DllCall("oleacc\LresultFromObject", "ptr", IDispatch, "ptr", 0, "ptr", ObjPtr(client := { proxy: 0 }), "ptr")
exec := ComObject("WScript.Shell").Exec('"' ahkv1exe '" /ErrorStdOut *')
exec.StdIn.Write(Format("
(
	VarSetCapacity(IDispatch, 16), NumPut(0x46000000000000c0, NumPut(0x20400, IDispatch, "int64"), "int64")
	DllCall("oleacc\ObjectFromLresult", "ptr", {}, "ptr", &IDispatch, "ptr", 0, "ptr*", idisp := 0), ComObject(9, idisp).proxy := [], ObjRelease(idisp)
	msgbox
)", lresult)), exec.StdIn.Close()
while exec.Status = 0 && !client.proxy
	Sleep(10)
if !exec.Status
	a := client.proxy
```
This is v2 code.
This happens when you get a v1 COM object.

**Comment by thqby** [comment]
`aa := a._NewEnum()`
![image](https://user-images.githubusercontent.com/28240311/149710426-b81a6691-82a2-4b04-98b4-62a778d1b3d9.png)

**Comment by zero-plusplus** [comment]
Thank you for the information.

I was able to fix it so that it displays the correct values.
I have also fixed the issue of 4 errors when trying to get a child element of a ComObject in data inspection.

The release containing the fix may take a little longer as I plan to make other fixes as well.

**Comment by zero-plusplus** [comment]
I noticed that the `DispatchType` and `DispatchIID` of `a` and `aa` in your example are empty even after the fix.
This seems to be a specification, as it was the same with SciTE4AutoHotkey.

**Comment by thqby** [comment]
That's why there is a value displayed above, but the subkey is empty?

**Comment by zero-plusplus** [comment]
The following is the XML strings returned by the debugger.
```xml
<?xml version= "1.0" encoding= "UTF-8"?>
<response command= "property_get" transaction_id= "28">
  <property name= "a" fullname= "a" type= "object" facet= "" classname= "ComObject" address= "11040320" size= "0" page= "0" pagesize= "10000" children= "1" numchildren= "4">
    <property name= "Value" fullname= "a.Value" type= "integer" facet= "" children= "0" encoding= "base64" size= "8">MTEyMzY0MDg=</property>
    <property name= "VarType" fullname= "a.VarType" type= "integer" facet= "" children= "0" encoding= "base64" size= "1">OQ==</property>
    <property name= "DispatchType" fullname= "a.DispatchType" type= "string" facet= "" children= "0" encoding= "base64" size= "0"></property>
    <property name= "DispatchIID" fullname= "a.DispatchIID" type= "string" facet= "" children= "0" encoding= "base64" size= "0"></property>
  </property>
</response>
```

**Comment by thqby** [comment]
From this point of view, XML has subkey values.

**Comment by thqby** [comment]
This should be AHK's bug.
In one of the returned XML, `a.Value` and `a.VarType` are marked as `string`.

**Comment by thqby** [comment]
I have found the reason. V1 ComObject::Invoke is always successful, so the subkey a.value is overwritten.
Similarly, in V2, if `value` of `comobject a` exists, it will also override the subkey `a.value`.
for example:
```
NumPut("int64", 0x20400, "int64", 0x46000000000000c0, IDispatch := Buffer(16))
lresult := DllCall("oleacc\LresultFromObject", "ptr", IDispatch, "ptr", 0, "ptr", ObjPtr(client := { value: 0, vartype: 0 }), "ptr")
DllCall("oleacc\ObjectFromLresult", "ptr", lresult, "ptr", IDispatch, "ptr", 0, "ptr*", a := ComValue(9, 0))
```

**Comment by zero-plusplus** [comment]
Thanks for the information.

I'm not familiar with low-level programming(?) such as C++ or COM, so it's difficult to understand, Is there any way to work around the issue of `DispatchType` and `DispatchIID` being empty?

**Comment by thqby** [comment]
I think [c]DispatchType[/c] and [c]DispatchIID[/c] can only be obtained when the COM component is registered in the system.

**Comment by zero-plusplus** [comment]
Thank you.

Your guess is that it's a specification rather than a bug, so I guess I don't need to think about workarounds.

**Comment by zero-plusplus** [comment]
This issue also seems to occur with watch expression and log point.

When registering a.Value to a watch expression, AutoHotkey will display an error message in the message box.
In this case, the watch expression will be unavailable until VSCode is restarted.

This is a little similar to #190.

**Comment by zero-plusplus** [comment]
I just released a fixed version. Please check it out.
