### ISSUE TITLE
Conditional breakpoint not working with embedded quotes in string

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#19]
![image](https://user-images.githubusercontent.com/1964198/86294479-370afe80-bbba-11ea-8147-ff46000c3365.png)

I tried different ways but could not find a way to break on this string value (quotes are part of the string): "_Object"

**Comment by zero-plusplus** [comment]
Strings with single quotes are not yet supported.

It will be supported in the next version.

**Comment by SAbboushi** [comment]
Thank you.  Can you also add support for escaped quotes e.g.: "`"_Object`""?

**Comment by zero-plusplus** [comment]
I guess your example is not escaped. Is it `` "`"_Object`"" ``?
I've made it possible. I checked, but it seems to be working.

**Comment by SAbboushi** [comment]
> Your example is probably not escaped with `` ` ``. Is it `` "`"_Object`"" ``?

That is my example.  I understand that in AHK, it is [escaped](https://lexikos.github.io/v2/docs/misc/EscapeChar.htm)


> I've made it possible. I checked, but it seems to be working.

It did not work in past version.  Do you mean it is working in next release?

**Comment by zero-plusplus** [comment]
I found some bugs, but your example itself is working version 1.4.4.

Maybe the intention is not conveyed.
I am checking in the following way.
```
; foo.ahk
foo := "`"_Object`""
```
```
# conditional breakpoint
foo == "`"_Object`""
```

**Comment by SAbboushi** [comment]
EXCELLENT!! Thank you again!
