### ISSUE TITLE
MsgBox disables debugger?

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#2]
```
MsgBox 1
x := 2
Msgbox 2
```

When `MsgBox 1` is displayed, I see that Debugger seems to temporarily stop working properly

1) VARIABLES pane (and other panes e.g. CALL STACK) become blank/empty:
![1  Panes empty](https://user-images.githubusercontent.com/1964198/83952312-b0067880-a7fd-11ea-9aed-808d925bc417.png)

2) Pause button does not seem to work

In SciTE4AutoHotkey, when `MsgBox 1` is displayed, I would 
1) click PAUSE button
2) click "MsgBox 1" OK button

SciTE4AutoHotkey would stop execution and make `x := 2` the next line for execution

In my simple example code above: when `MsgBox 1` is displayed, I can then add a breakpoint to `x := 2` line and code execution will pause after I click "MsgBox 1" OK button.

But with big program, it may not be easy to know which line number MsgBox command is on; and since Debugger VARIABLES and other panes are empty, I have no information to know the current line of code.

**Comment by zero-plusplus** [comment]
**I am translating from Japanese to English with Google Translate.**

Thank you for reporting.
Before 1.2.0, PAUSE button did not work.
The develop branch has already fixed this issue.

Please be patient as we will release 1.3.0 as soon as testing is completed.

**Comment by zero-plusplus** [comment]
1.3.0 has been released. Please check if the problem has been fixed.

**Comment by SAbboushi** [comment]
Excellent - pause button now works.  

Note: Run panes are still empty when MsgBox is displayed e.g. VARIABLES pane is empty until after I click pause button.  I will create new Issue for this.
