### ISSUE TITLE
Enhanced detection of v2 default runtime

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#218]
Installers have been added since [a2.0.beta-4](https://www.autohotkey.com/boards/viewtopic.php?f=24&t=95688#p466061).
This installer is installed in the path `AUTOHOTKEY_INSTALL_DIRECTORY/VERSION` if v1 is installed.

Current default runtime is fixed at `AUTOHOTKEY_INSTALL_DIRECTORY\v2\AutoHotkey.exe`, so the above directory must be detected and set.

**Comment by Lexikos** [comment]
> if v1 is installed

**Only** the legacy v1 installer (or the user) places exe files in the root of the installation directory. Even if v1 is not installed, the v2 exe files are placed in a version-specific subdirectory.

If the new installer runs as admin, it creates a symbolic link at `v2` pointing to the latest v2 subdirectory. This was partly intended for compatibility with tools like your extension. I think I intended to create a `v2\AutoHotkey.exe` link as well, but must have forgotten.

The new installer supports non-admin installs, in which case a symbolic link cannot be created.

The "default" exe used by the launcher may depend on settings stored under `HKCU\Software\AutoHotkey\Launcher`. By default it finds the exe with the latest version, preferring x64 if applicable. I thought of adding a command line switch to the launcher to ask it which exe to use for a given script, or to list the available exes (which would mean other tools don't need to duplicate its logic, and the logic can be updated easily). Let me know if you think any change like that would help your extension, as it may help other tools as well.

**Comment by zero-plusplus** [comment]
> Only the legacy v1 installer (or the user) places exe files in the root of the installation directory. Even if v1 is not installed, the v2 exe files are placed in a version-specific subdirectory.

Thank you. I was mistaken.

---

I like the idea of adding symbolic links to the `v2` subdirectory.
It makes it unnecessary to implement the version search logic ourselves.

Symbolic links will be available in the next version?

**Comment by zero-plusplus** [comment]
Thanks, I confirmed the symbolic link to `v2` in v2.beta-5.

However, it seems that the runtime detection process does not support symbolic links and needs to be fixed.

I am closing this issue to use [this one](https://github.com/zero-plusplus/vscode-autohotkey-debug/issues/227).
