### ISSUE TITLE
Add `/CP65001` to the default value of runtimeArgs

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#219]
Add an argument to make UTF-8 the default encoding used to load scripts.

This will allow source code containing multibyte strings to be executed correctly.

**Comment by zero-plusplus** [comment]
The reason I decided to make UTF-8 the default is that when I was a beginner who did not yet know character encoding, I had a very difficult time finding out why source code containing multibyte strings could not be invoked.

However, I decided to revert this change because it would cause similar difficulties for users who do not use UTF-8.

Debugging via Launcher does not seem to be able to retrieve streams such as stdout, so any changes made to Launcher would not be reflected in the extension here.

I've come up with the idea of enabling this setting only when the `runtime` encoding is UTF-8 as one solution, but what about this?

There are two issues with this: the encoding may or may not be read correctly, and this behavior is set automatically and cannot be changed by the user.

But, I don't think the second is much of a issue, though, since I don't think anyone doesn't want to use the UTF-8 setting while using UTF-8 for encoding.

**Comment by Lexikos** [comment]
> Debugging via Launcher does not seem to be able to retrieve streams such as stdout

I'm not sure what you mean exactly, but I do not think this is a limitation of the launcher or AutoHotkey. Stdout output from the actual script is echoed by the launcher regardless of whether there is a debugger connection. I have confirmed this by using a command line like `v2\AutoHotkey.exe UX\launcher.ahk /Debug Script.ahk | more` and [dbgp_console.ahk](https://github.com/Lexikos/dbgp/blob/master/dbgp_console.ahk).

I assume you would be redirecting stdout of the launcher process, while receiving a TCP connection from the actual script process (not the launcher process). Maybe this causes an issue for your extension.

For tools that are aware of the launcher, I considered that it might be better for the launcher to provide command-line usage that passes back the identified version, the path to the interpreter, and any proposed command line switches (such as /cp65001) for launching the script. In other words, you call the launcher to determine how to launch the script, then you launch the script directly. (Or you can call the launcher just to determine which version of AutoHotkey the script is for.)

**Comment by zero-plusplus** [comment]
If the launcher echoes the message being debugged, then debugging using the launcher may be possible.

I will try this when I have time.

**Comment by Lexikos** [comment]
I presume your extension reads the actual stdout stream. If it was redirecting stdout with `stdout -c 2`, that would also work because it comes through the DBGp connection, which is made between the actual script and the DBGp client (extension). That also works if you attach to a running script.

**Comment by zero-plusplus** [comment]
Thanks for the info. 
Newly opened [issue](https://github.com/zero-plusplus/vscode-autohotkey-debug/issues/241) on debugging with launcher.

---

I'm closing this because I opened an [alternative issue](https://github.com/zero-plusplus/vscode-autohotkey-debug/issues/240).
