### ISSUE TITLE
Error when specifying symbolic link in `runtime` attribute

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#227]
Beginning with [v2-beta5](https://www.autohotkey.com/boards/viewtopic.php?f=24&t=95688#p468737), the installer now adds a symbolic link to the latest version of AutoHotkey under the name v2 when installed.

Currently the extension does not recognize this symbolic link and raises an error.

**Comment by zero-plusplus** [comment]
The error was unrelated to the symbolic link.

The error was due to my mistaken belief that the installer was placing `AutoHotkey.exe`.

In fact, it was suffixed with a bit number, such as `AutoHotkey64.exe`.

Specifying the correct path, such as `v2/AutoHotkey64.exe`, worked fine.

So I close this issue.

**Comment by Lexikos** [comment]
> The error was due to my mistaken belief that the installer was placing AutoHotkey.exe.

v2.0-beta.7 also creates an `AutoHotkey.exe` symbolic link.

**Comment by zero-plusplus** [comment]
Thank you for creating the symbolic link.

This is not a problem for non-administrator installations, as the user must specify it himself.

It does not appear necessary to change the `runtime` defaults as it is.

**Comment by Lexikos** [comment]
Do you mean that the user has to specify the location anyway?

The way I see it, if the user must manually specify the location of AutoHotkey even though it is recorded in the registry, that *is* a problem, especially if it must be done each time the user creates a new workspace.

I think most users will be using an admin install, though.

**Comment by zero-plusplus** [comment]
I didn't know if it was possible to access the windows registry from Node.js, so I did some research.
Apparently, it is possible with the following package.

https://www.npmjs.com/package/windows-registry

However, I feel that including this in the project would have more disadvantages than advantages, as it would require a build tool during `npm install`.
Therefore, I do not intend to implement automatic specification of runtime other than admin install at this time.

---

In the future, I plan to allow you to specify the runtime from user settings, so you only need to set it once.
