### ISSUE TITLE
`extend` in `launch.json` doesn't carry `useAnnounce`

### ISSUE THREAD

**Issue by anonymous1184** [zero-plusplus/vscode-autohotkey-debug#233]
Debug directives on includes need `useLoadedScripts` and permanently debug like that is a bit slower, so I have two profiles one quick debugging and one for a more in depth debug (through `extend`). I noticed the `extend` option is not carried to the extended profile.

Here's a simple testing pair:

```json
{
    "name": "Test",
    "request": "launch",
    "type": "autohotkey",
    "useAnnounce": "error",
    "useDebugDirective": true,
    "useLoadedScripts": true
},
{
    "extends": "Test",
    "name": "Test (deep)",
    "useDebugDirective": true,
    "useLoadedScripts": { "scanImplicitLibrary": true },
    "usePerfTips": { "format":"{{elapsedTime_ms}}ms" }
}
```

Also on a quick side note (I don't know if this is the extension or VSCode) the extended profile works fine without `request` and `type` but the `launch.json` validation marks their absence as warning. And that's totally not worth of creating a new issue because it might not be the extension after all.

**Comment by zero-plusplus** [comment]
I tried but could not confirm the issue.
In my environment, useAnnounce was successfully extended to `Test (deep)`.

---

Since vscode completes attributes using request and type, it is recommended to define them.
