### ISSUE TITLE
Improvements, including disruptive changes to log points

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#237]
The format to output the current variable is as follows.
* `{AutoHotkeyVariableName}`
* `{Object:DEPTH}`
* `{{MetaVariableName}}`

With the change in the [evaluation method](https://github.com/zero-plusplus/vscode-autohotkey-debug/issues/116) for conditional breakpoints, I would like to make the following changes.
* `{expression}`

Expressions will support four arithmetic operations, functions, etc., as shown in the example following.

```ahk
;  basic arithmetic operations
num_1 := 1
num_2 := 2
; @Debug-Output => {num_1 + num_2} = 3

; Object Manipulation
obj := { a: "a", b: "b" }
; @Debug-Output => {ObjCount(obj)} = 2
; @Debug-Output => {ToYaml(obj)}

; The following is an alternative to `{Object:DEPTH}`
obj2 := { a: { b: { c: { d: "" } } } }
depth := 3
; @Debug-Output => {Retrieve("obj2", depth)}

; The following is an alternative to `{{MetaVariableName}}`
; @Debug-Output => {Retrieve("{hitCount}")} = 2
```

**Comment by Lexikos** [comment]
This approach seems like it could be quite powerful, with the appropriate functions.

I have been looking for a way to output a numeric value as hex. Visual Studio permits this with [format specifiers](https://docs.microsoft.com/en-us/visualstudio/debugger/format-specifiers-in-cpp?view=vs-2022) such as `{dwFlags,x}` to print dwFlags as hex within a breakpoint message, or just `dwFlags,x` in a watch. Something like `{hex(dwFlags)}` would fit with your idea above, although not as convenient.

**Comment by zero-plusplus** [comment]
I had never heard of format specifiers before. Thanks for the information.

This Issue relies on the creation of a parser, so implementation is quite a ways off.

However, I think format specifiers are a very good idea because they are easy to implement and can be used without modification after the Issue is implemented.

Opened as a separate [issue](https://github.com/zero-plusplus/vscode-autohotkey-debug/issues/244) on format specifiers.
