### ISSUE TITLE
Wish "useOutputDebug" to support not only \n but also \t or anything else.

### ISSUE THREAD

**Issue by PythonYunfei** [zero-plusplus/vscode-autohotkey-debug#277]
Wish `useOutputDebug` to support not only `\n` but also `\t` or anything else.

**Comment by zero-plusplus** [comment]
I am not sure what kind of problem you are experiencing.

Can you provide specific launch.json contents or source code where the issue occurs?

**Comment by PythonYunfei** [comment]
![image](https://user-images.githubusercontent.com/47076058/212074595-32e0ead6-892a-43ab-9352-50f89d5d16a4.png)
I hope that I could be given an option to set it to be a `"Tab"` as well instead of a line feed which I cannot type out both of them in GitHub. Then when to wrap a line will still be up to me when I write it in `outputdebug`.  Because a line feed is not the only thing in debug console, perhaps `"Tab"` will appear much more in some situations.  It would be much more convenient jif you could give a `"Tab"` or something else for `useOutputDebug`.

**Comment by PythonYunfei** [comment]
![image](https://user-images.githubusercontent.com/47076058/212080789-c6db4d37-623d-4e93-abc7-2384795269fe.png)
I hope that I could be given an option to set it to be a `"Tab"` as well instead of a line feed, both of which I cannot type out in GitHub. Then when to wrap a line will still be up to when I write it in `outputdebug`.  As the debug console is much wider than high, line feeds are not the only things in it, perhaps `"Tab"` will appear much more in a significant part of situations.  It would be much more convenient if you could give a `"Tab"` or something else for `useOutputDebug`.

**Comment by zero-plusplus** [comment]
I still don't understand the request a bit.
Do you mean you want the message to wrap at the time the tab appears?

In other words, do you want the output to be as follows.

```
3
4
5
7
9
```

**Comment by PythonYunfei** [comment]
No, on the contrary, I want the output to be like this automatically without `'n` pointed by the arrow below:
![image](https://user-images.githubusercontent.com/47076058/212134884-24773682-f89a-4408-ace5-09a51093d51b.png)

**Comment by PythonYunfei** [comment]
To be honest, the plugin works pretty well yet that is the best debug plugin for AHK.  I simply would like to try to pull some suggestions just to make the plugin truly become even better if could.

**Comment by zero-plusplus** [comment]
I understood.

The useOutputDebug was originally intended to add an attribute to insert a `prefix` and `suffix` string to the output message, but was not adopted.

It seems that adding this attribute would satisfy the request.

I am currently working on a major update and these will not be added until at least March or later.

---

I cannot always accommodate requests, but suggestions are always welcome.

**Comment by PythonYunfei** [comment]
No matter, any time, and thank you for your great work. For you to do the most important things first is a must. And I also think it is a good suggestion because `'t` is nothing special compared to `'n` as a `suffix`.  Waiting for your good news.

**Comment by zero-plusplus** [comment]
This issue is tracked [here](https://github.com/zero-plusplus/vscode-autohotkey-debug/issues/278). Therefore, I close this issue.
