### ISSUE TITLE
Add a MetaVariable

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#28]
It provides the user with information that can be retrieved by the debugger adapter.
I will call this a `MetaVariable`.

`MetaVariable` can be used for conditional breakpoints, log points, etc.
If they are used, the name of the variable is enclosed in curly braces. e.g. `{MetaVariableName}`.
However, log point must be double enclosed. e.g. `{{MetaVariableName}}`
Also, it is not case sensitive.

# List of meta variables
* Contextual information for the script
  * `file` : File name. Equivalent to `A_LineFile`.
  * `line` : line number. Equivalent to `A_LineNumber`.

* Information held by the debugger adapter
  * `executeTime_` : The time it took to execute. The following units are added at the end: `s`(second), `ms`(millisecond), `ns`(nanosecond). e.g. `elapsedTime_s`
  * `condition` : Condition of the breakpoint
  * `hitCondition` : Condition of the hit breakpoint
  * `logMessage` : Message of the log point

* Process information. You can use it by setting `useProcessUsageData` to true. The reason it is optional is because it takes time to get the data
  * `usageCpu` : CPU usage(%).
  * `usageMemory_` : The memory being used. The following units are added at the end `B`(Byte), `MB(Megabyte)`

**Comment by SAbboushi** [comment]
Very good - you have been busy!  I am glad to see your continued work - thank you.

**Comment by zero-plusplus** [comment]
Thanks.

I feel like making the work visible has made it clearer and more efficient for me to do what needs to be done.

I was working on it right from the last update and editing the source code without thinking, which made the commits more granular and less efficient.

I realized that milestones and issues are great inventions.
