### ISSUE TITLE
It seems that useTrailingLinebreak can not work anymore in useOutputdebug

### ISSUE THREAD

**Issue by PythonYunfei** [zero-plusplus/vscode-autohotkey-debug#280]
It seems that `useTrailingLinebreak` can not work anymore in `useOutputdebug`. I set the launch like this;
![image](https://user-images.githubusercontent.com/47076058/213487994-d146e371-01d0-47b7-a8a1-3e573e01d8e3.png)
But it seems that it does not make any difference. Is there something wrong in my settings, or in the plugin either?

**Comment by zero-plusplus** [comment]
Specify as follows.

```
"useOutputDebug": {
  "useTrailingLinebreak ": true
}
```

The `useOutputdebug.useTrailingLinebreak` just represents the hierarchical structure.

This notation is used because it is not possible to express hierarchical structures well using tables.

These attributes can be conveniently completed by pressing `Ctrl + Space`.
Also, these errors should normally generate warnings or errors, but have you had any of these messages?

**Comment by PythonYunfei** [comment]
Thank you very much.  I feel so sorry for bothering you with this question.🤣

> These attributes can be conveniently completed by pressing Ctrl + Space.
`Ctrl + Space` does not work but it will show suggestions if I type letters within the quote.

> Also, these errors should normally generate warnings or errors, but have you had any of these messages?
No, it doesn't.  But `“type”` will:
![image](https://user-images.githubusercontent.com/47076058/213628851-78c1bcf4-f94c-47d4-8ddc-f80209bbb0c6.png)

**Comment by PythonYunfei** [comment]
> These attributes can be conveniently completed by pressing Ctrl + Space.

I have known the reason.  Because it will change the language of the input method when pressing `Ctrl+Space`.  A change of keybind for `Ctrl+Space` will solve it.

**Comment by zero-plusplus** [comment]
It may depend on the Windows configuration language. My completion feature was `Ctrl + Space` by default.

> No, it doesn't. But will:“type”

I have also checked and it appears that child attributes do not display any warnings or other messages.

I will check if this is a specification or my mistake.

**Comment by PythonYunfei** [comment]
Thanks for hard and sometimes trivial work.

**Comment by zero-plusplus** [comment]
> > No, it doesn't. But will:“type”
>
> I have also checked and it appears that child attributes do not display any warnings or other messages.

I will check if this is a specification or my mistake.

This issue was still a bug. You can track it [here](https://github.com/zero-plusplus/vscode-autohotkey-debug/issues/283).
