### ISSUE TITLE
Suggestion: Add 't or something else to the judgment for determination of whether to break line

### ISSUE THREAD

**Issue by PythonYunfei** [zero-plusplus/vscode-autohotkey-debug#281]
Add `'t `or something else to the judgment for determination of whether to break lines.
![image](https://user-images.githubusercontent.com/47076058/213674692-47d73895-aec5-47e7-9aba-787015f2e011.png)
As we can see, it will break lines as usual, even when a `'t` is following what I prepare to output.  It is redundant in this situation that `'t` has broken it.  So I wish it can break line automatically and at the same time I could also use several `'t` or several splitting symbols else within one line.
It would be better if you could add an additional option for judgment which contains more than one splitting symbols, not only `'n` but also `'t` or ``s`s` etc. for judgment.
![image](https://user-images.githubusercontent.com/47076058/213685745-7011c2c3-832b-499e-9af6-0c4e12303cc4.png)

**Comment by zero-plusplus** [comment]
Do you want the line to normally line break, but not if it ends on a particular character?

If so, such requests are probably rare cases.

The solution I think is to control all the line breaks yourself without using useTrailingLinebreak. Alternatively, you can store the message in a variable as follows.

```ahk
message := "1`t"
message .= "2`t"

OutputDebug(message)
```

**Comment by PythonYunfei** [comment]
> Do you want the line to normally line break, but not if it ends on a particular character?

Sure.

In my opinion, this feature can be perfectly combined with feature #278. For example, if you set `'t` as the `TrailingLineBreak` instead of `'n`, then you should type "`n" explicitly for a line wrap. So the feature will be certainly needed, every time you type `'n` or sometimes `'t` at the end of output. It is not that rare, I think. The same will apply to the situation too where `'n` is set as the default `TrailingLineBreak`. All you need to do is just extend the judgment below:
![image](https://user-images.githubusercontent.com/47076058/213745784-4d7f5305-07b0-498d-9383-51221fed1c3a.png)
Just adding `'t` which is used frequently, to the judgment, will also be enough.  Adding an optional setting for users is not a must.

**Comment by zero-plusplus** [comment]
OutputDebug outputs debug messages.

How the messages should be displayed is not determined and is left to the editor or extension that receives and displays the messages.

For example, SciTE4AutoHotkey does not insert a line break in each message, while DebugView does.

The `useTrailingLinebreak` is intended to absorb this difference.

Debug messages should be displayed as similarly as possible no matter which editor is used, so it is not possible to add special specifications that are unique to this extension.

With this in mind, I probably shouldn't add the `prefix` and `suffix` that I was talking about adding the other day.

**Comment by zero-plusplus** [comment]
May I close this?

**Comment by PythonYunfei** [comment]
Sure.

**Comment by zero-plusplus** [comment]
ok
