### ISSUE TITLE
[IMPORTANT] Support `AutoHotkey v2.0.14+`

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#327]
~~Due to a major change in the debugger specification in [AutoHotkey v2.0.14](https://www.autohotkey.com/boards/viewtopic.php?f=24&p=570714&sid=4ff9f0b737d71e6de6dcef73b26f3173#p570714), this extension no longer features correctly.~~

~~This problem will be resolved in vscode-autohotkey-debug v2.0.0, but it will take some time before release as the source code is being rewritten from scratch.~~

I have changed my policy to provide hotfixes to support AutoHotkey v2.0.14+ in v1.11.x for a while.

Note that it is speed-oriented and will be released with minimal testing, so it may contain bugs.

**Comment by Lexikos** [comment]
What major specification change broke the extension? There are multiple debugger engine bugs in v2.0.14. I specifically chose not to make any changes which should have prevented the extension from working, because I use the extension.

**Comment by zero-plusplus** [comment]
Each property of the object is not obtained as described [here](https://github.com/zero-plusplus/vscode-autohotkey-debug/discussions/324#discussioncomment-9380224).

I had mistakenly assumed that this was occurring due to destructive change.
