### ISSUE TITLE
Add IntelliSense using information from the debugger

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#40]
It should be technically possible since you can get a list of variables, and since just using the VSCode API, the implementation difficulty should be low.

Since I often modify the source code during debugging, I think this feature is quite useful.

**Comment by SAbboushi** [comment]
>> Since I often modify the source code during debugging
Me too, actually almost always

>>I think this feature is quite useful.
Agreed

**Comment by zero-plusplus** [comment]
In v2, a critical error may occur when retrieving with dynamic properties via the debugger.
I therefore decided that it was inappropriate to enable this feature by default.

To use it, `useIntellisense` should be set to `true`.

**Comment by SAbboushi** [comment]
>> In v2, a critical error may occur when retrieving with dynamic properties via the debugger.
That is unfortunate...

**Comment by zero-plusplus** [comment]
It seems that if a dynamic property returns a backing field and it is a string, the following error occurs.
`Critical Error: Invalid memory readwrite`

**Comment by zero-plusplus** [comment]
Good news.
I found a way to avoid the error.

This allows you to use IntelliSense safely as long as the user doesn't cause an error in the dynamic properties.

**Comment by zero-plusplus** [comment]
Now that the disadvantages have been resolved, we enable it by default and remove `useIntellisense`.

**Comment by SAbboushi** [comment]
GREAT!!
