### ISSUE TITLE
Remove `useAdvancedBreakpoint` and enable it by default

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#41]
Unless the user sets conditions, hit conditions and log messages, it does not affect the speed of processing. It is therefore redundant to have to change the settings in order to use it.

The configuration was intended to highlight the disadvantages of using it, but I find the description in the README to be sufficient.

Therefore, I need to remove the setting itself and change it so that it is always enabled.

Another reason is that Advanced breakpoint is a term that includes Function Breakpoint #31.

Function breakpoints have different disadvantages than the other Advanced breakpoints and should not be enabled or disabled in a single setting.

**Comment by SAbboushi** [comment]
very good
