### ISSUE TITLE
Add Output directive comment

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#42]
Set a log point at the location of the comment that follows the rules. This log point is not visible in the UI and cannot be changed.
```
; @Debug-Output:LEVEL:GROUP(CONDITION)[HITCONDITION] => MESSAGE
```

## LEVEL (optional)
The `LEVEL` is as follows, in descending order of level
  * `INFO`
  * `WARN`
  * `ERROR` 
  * `FATAL`

## GROUP (optional)
The `GROUP` is as follows.
* `start`: Start a group
* `startCollapsed`: Start a group. Unlike `start`, the output is collapsed.
* `end`: End a group

## => (optional)
`=>` is Output operator. The following types are available.
* `->`: Message without newline. leading spaces are removed
* `=>`:  Message with newline. leading spaces are removed
* `->|`:  Messages without newline. Also, no leading spaces are removed
* `=>|`:  Messages with newline. Also, no leading spaces are removed

## Settings
To enable this feature, add `useOutput` to `useDirectiveCommnet` in launch.json.
The following types can be configured for `useOutput`.
* `boolean`:  If true, logs all `LEVEL`; if false, no logs are output
* `string`:  Specifies the `LEVEL` to be output. The `LEVEL` below the specified one will also be output. In other words, if you specify `WARN`, it outputs `INFO` and `WARN`
* `array`: Use this if you want to select the complete level to be output. If you set `[ "WARN", "ERROR"]`, only `WARN` and `ERROR` will be output

## Advantages of this feature
Compared to outputting logs directly with AutoHotkey, such as OutputDebug, this has the following advantages
* Can change the color of the log according to the level. Currently vscode seems to be able to be color-coded in three different ways.
* Logs can be grouped. The objects are easier to see
* Can select the log output depending on the level
* If you don't go through the debugger, it's just a comment and no extra processing is involved. This means there are no bugs in the log output code

## Disadvantages of this feature
* Runs a slower at startup due to the need to search for directive comments
* The performance of the execution is inevitably slowed down by the fact that the script is stopped to output the log

**Comment by SAbboushi** [comment]
I believe there is a typo: `useDirectiveCommnet` should be `useDirectiveComment`?

**Comment by zero-plusplus** [comment]
The only typo was here.
It's fine on the source code.

I'll check again to see if there are any typos that affect the user, like this one. Thanks.
