### ISSUE TITLE
Loaded files are not detected when on previous #Include line a directory is specified

### ISSUE THREAD

**Issue by Toralf-AHK** [zero-plusplus/vscode-autohotkey-debug#44]
Loaded files are not recognized when on previous #Include line a directory is specified.
See [Include FileOrDirName](https://www.autohotkey.com/docs/commands/_Include.htm)
`Directory: Specify a directory instead of a file to change the working directory used by all subsequent occurrences of #Include `

**Comment by zero-plusplus** [comment]
I didn't know about that feature.

When I checked the source code to add the feature, I found some bugs, so I'll open the issue separately.

**Comment by zero-plusplus** [comment]
Fixed it in the develop branch. Thanks for the report.

However, the next release may take a little longer.

**Comment by zero-plusplus** [comment]
Thank you for your patience.
I've just uploaded a new version that fixes this issue. Please check if it has been fixed.
