### ISSUE TITLE
Error occurs when getting dynamic properties by data inspect, etc

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#51]
The following errors occur.
`Critical Error: Invalid memory read/write`

I thought it was an unsolvable problem, but I found a way around it and will fix it.
However, it does not resolve errors that occur when dynamic properties are overridden.

This allows advanced breakpoints and [IntelliSense](https://github.com/zero-plusplus/vscode-autohotkey-debug/issues/40) to be used safely.
But, if a runtime error occurs in a dynamic property, the script is stopped. This is a specification and cannot be avoided.

**Comment by SAbboushi** [comment]
Good job!
