### ISSUE TITLE
Returns false whenever the condition is set to a string containing `&` and `|`

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#53]
It seems to be a bug originating from the `&&` and `||` operators and has been occurring since 1.5.0.

It occurs when the following conditions are set. `variable == "|"`

**Comment by SAbboushi** [comment]
Wow - it seems your debugger adapter has become a full-time project for you?

**Comment by zero-plusplus** [comment]
I'm not familiar with the recursive parser, so I fixed it with force.
I hope there are no new bugs.
