### ISSUE TITLE
Add an option to auto jump to the source of the error

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#54]
When an error occurs, it outputs a link to jump to the source of the error.
However, it's a bit cumbersome when a lot of errors occur, such as porting a v1 script to v2.

That's why I came up with the option to automatically jump to the source when an error occurs and the script ends.

The implementation itself is simple, but there are a few things to think about.
1. Does the option name `useJumpToError` adequately describe this feature? Otherwise, I'll need to come up with a more understandable name.
2. This feature conflicts with `openFileOnExit`. I'll need to decide what to do in that case. However,  I believe that this feature should take precedence because most people will focus on the source of the error.

I thought about enabling this feature by default, but that idea was scrapped because many people would be confused if they tried to manipulate the editor without telling the user.

**Comment by zero-plusplus** [comment]
`openFileOnError` may be more consistent. 
However, while `openFileOnError` is a boolean, `openFileOnExit` may be complicated because it is a string.

**Comment by CA10C3SAR** [comment]
Does this option already exist? How do I activate it?

**Comment by zero-plusplus** [comment]
This is still a draft and has not been implemented.
I am currently busy developing [another project](https://github.com/zero-plusplus/vscode-autohotkey-debug/discussions/90), so I have stopped adding new features.

In the meantime, please use the link to the error source displayed in the debug console (e.g. `C:\example.ahk:123`).
You can jump to this link by holding down Ctrl and clicking on it.

**Comment by zero-plusplus** [comment]
I implemented this in version 1.7.0.
If you want to use it, please add `useAutoJumpToError: true` to launch.json.
