### ISSUE TITLE
Make ErrorStdOut a UTF-8 by default

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#56]
ErrorStdOut has been extended to allow setting Encoding in [1.1.33.00](https://www.autohotkey.com/docs/commands/_ErrorStdOut.htm) or [v2.0-a112](https://lexikos.github.io/v2/docs/commands/_ErrorStdOut.htm) and above.
However, it now requires each user to set the `runtimeArgs` to use it.

This is a little inconvenient. So check the version and If it can use Encoding, setting UTF-8 by default.

**Comment by zero-plusplus** [comment]
In order to know the version of AutoHotkey before run script, it seems that need to use a different programming language.
In that case the cost of installation will be significant as it will have to be compiled.
This means that will need to consider other means.

So the first thing I thought of was to use `ErrorStdOut=UTF-8` to get the script to run, and if an error occurs, change it to `ErrorStdOut` and run it again.
For now, I'll try to implement this.

**Comment by zero-plusplus** [comment]
Hmmm. This method seems to be a no, as it brings up an error dialog.
After all, it seems that each user needs to set up `runtimeArgs`.

I'm going to close it because I can't think of any other way to do it.

**Comment by SAbboushi** [comment]
So I would add `"runtimeArgs": "/ErrorStdOut=UTF-8"` to launch configurations?

**Comment by zero-plusplus** [comment]
Yes.

**Comment by zero-plusplus** [comment]
This remined me that Can get a version by using [this](https://www.autohotkey.com/docs/commands/Run.htm#ExecScript).

**Comment by zero-plusplus** [comment]
Setting ErrorStdOut to UTF-8 is not enough to fully address garbled characters, need to add `/CP65001` to the argument of AutoHotkey.
