### ISSUE TITLE
If the script exits without stopping at a breakpoint, etc., the message containing the object is not printed correctly.

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#57]
This means that the output directive does not work properly and needs to be fixed in `1.6.0`.

However if want to look at a child element, the debug adapter must be running, so this issue is not fatal.

Is there any benefit to outputting the object in the first place?
If you want to check a specific object, you should basically use the Watch expression.

It has the advantage of being able to record objects in a particular call stack, but does anyone actually use it for that purpose?

The ability to output objects is described in the README as a benefit and needs to be reviewed.

**Comment by zero-plusplus** [comment]
I've tried many things but could not solve this.

I'm sure the message has been sent, so I don't think it's a mistake on our part. However, I have not been able to gather enough information to be sure of that.

I have decided that this issue cannot be resolved quickly enough.
I will mention this in README and close this issue.

**Comment by zero-plusplus** [comment]
I was able to fix it.

**Comment by SAbboushi** [comment]
That's wonderful!  Good work.

**Comment by zero-plusplus** [comment]
Thanks.

I was supposed to release `1.6.0` today, but I found a bug related to simulating step execution when using Advanced breakpoint, so I am delaying it.

It is very complex and will take some time to test.

**Comment by SAbboushi** [comment]
May you have good luck with your testing
