### ISSUE TITLE
DEBUG CONSOLE: vscode errors need to be preceded with two new line characters

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#6]
Error message is appended to most recent output:
![image](https://user-images.githubusercontent.com/1964198/83983334-099c9f00-a8f3-11ea-938e-a519c6bca9fd.png)

My preference would be to also have a separation line, maybe something like:
```
123

------------------------------------------------------------------
Error:  This value of type "String" has no property named "y".

	Line#
	001: outputdebug(123)
--->	002: x.y := 3
	003: Exit
	004: Exit
```

**Comment by zero-plusplus** [comment]
Thanks for reporting.

I also like the dividing line. However, I don't know how to output it according to the width of the console.

If there is no way to do it, I will implement it with two line breaks.

**Comment by zero-plusplus** [comment]
I'm basically conforming to the Node debugger's specifications, but I checked and there's only one line break There were no blank lines in

In the debug console, the output is grouped by output, so blank lines may have been considered redundant.

It's not my preference, but I'm going to try to implement the same.
I decided that the Node debugger is more common and it is better.

**Comment by SAbboushi** [comment]
k thanks for posting information
