### ISSUE TITLE
Add a command that debug for the current file

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#70]
It is useful to set up the main script in `program` of `launch.json`.
However, when I'm testing the API, I often want to debug the current file.

It's a waste of time to switch settings each time.

To solve this, I need that add a command to debug the current file.
This command replaces `program` with `${file}` and starts debugging.

**Comment by zero-plusplus** [comment]
This problem is not only in AutoHotkey, but also in JavaScript, for example.
In other words, it seems better to start a separate project that solves this problem.

I''ll simply name it `vscode-custom-title-menu-bar`.
The title menu bar refers to where the button is displayed in the top right corner of the VSCode.

However, there is a problem with this project. The button has to be defined in the extension and cannot be customized by the user.

This means that if want to pseudo-customize it, need to assign a button and its corresponding command to each icon and allow the user to specify the action to be performed by a configuration file.

This takes a lot of time, but I don't have the time to do it.
I'll close this issue.

**Comment by SAbboushi** [comment]
> It is useful to set up the main script in `program` of `launch.json`.
> However, when I'm testing the API, I often want to debug the current file.

I don't understand: when is it useful to NOT have setting "program": "${file}"?

> It's a waste of time to switch settings each time.
By editing the launch.json?

I'm interested in understanding this because I don't use launch.json for settings

**Comment by zero-plusplus** [comment]
> By editing the launch.json?
> I'm interested in understanding this because I don't use launch.json for settings

You can configure multiple debugging configurations in launch.json, and 
I use the one to debug a specific file and one to debug open files settings as follows:
```
...
        {
            "name": "AutoHotkey Debug All Test",
            "type": "autohotkey",
            "request": "launch",
            "program": "${workspaceFolder}/test/AllTest.ahk",
        },
        {
            "name": "AutoHotkey Debug Selected",
            "type": "autohotkey",
            "request": "launch",
            "program": "${file}",
        },
...
```

> I don't understand: when is it useful to NOT have setting "program": "${file}"?

I use unit tests to test the API. Each test is divided into units of the test class and integrated in `AllTest.ahk`. This means that can test all APIs by debugging the `AllTest.ahk`. 

Let's consider editing and testing the API in this environment. If you have `${file}` set, you will always have to switch to the file of the corresponding test class.
However, if set the `AllTest.ahk` in the `program`, can start testing without switching files. This is an advantage.

Next, let's consider editing a test class and testing it. In this case, you only need to execute the test class you are editing. However, if the `program` is set to `AllTest.ahk`, I will have to run some useless tests.

I want a shortcut for debugging open files to get rid of this disadvantage.

It just eliminates the hassle of switching files, but it's surprisingly useful.

**Comment by SAbboushi** [comment]
Thanks for your explanation-

Samir

**Comment by zero-plusplus** [comment]
Does your message contain the content of the email from github?

**Comment by SAbboushi** [comment]
>> Does your message contain the content of the email from github?
Yes

I edited my response to get rid of the history.  

I decided to try responding by email instead of on github portal like I usually do.  Thanks for your question: it helped me realize the consequence.

**Comment by zero-plusplus** [comment]
ok.

Changing the subject, is there a minimum feature you want in `vscode-autohotkey`?
I'm thinking about releasing it early by putting off the time-consuming creation of the language server.

The following four things will be implemented.
* Syntax highlighting (already implemented but needs to be rewritten for future)
* Jump to an included file (already implemented)
* Intellisense of the Built-in API
* Jump to document

The jump to document you were requesting before is a feature that can be substituted with AutoHotkey, so I might put it off for later.

Here's a simple example. It works with the latest version of AutoHotkey 2.0-a122.
```ahk
#SingleInstance Force

#HotIf WinGetTitle("A") ~= "Visual Studio Code"
F1::jumpToDocument("https://www.autohotkey.com/docs/commands")    ; documention for v1
+F1::jumpToDocument("https://lexikos.github.io/v2/docs/commands") ; documention for v2
#HotIf

;{ Util
jumpToDocument(docUrlBase) {
  currentWord := getCurrentWord()
  Run(docUrlBase "/" currentWord ".htm")
}
getCurrentWord() {
  clip_bk := ClipboardAll()
  A_Clipboard := ""
  SendInput("^{Right}^+{Left}^c")
  ClipWait(1)
  currentWord := A_Clipboard
  clip_bk := A_Clipboard

  return currentWord
}
;}
```

**Comment by SAbboushi** [comment]
> Changing the subject, is there a minimum feature you want in `vscode-autohotkey`?

Thanks for your kind question.  I examined your [Project ](https://github.com/users/zero-plusplus/projects/1)today to try and understand, but I have some questions:

1. Is `vscode-autohotkey` a new extension but is the same code base as `vscode-autohotkey-debug`? 
2. Once `vscode-autohotkey` is released, then this replaces the extension `vscode-autohotkey-debug` meaning uninstall `vscode-autohotkey-debug` and install `vscode-autohotkey`?

> Syntax highlighting (already implemented but needs to be rewritten for future)

You mean alrady implemented by slevesque.vscode-autohotkey and dudelmoser.vscode-autohotkey2?

>Intellisense of the Built-in API

I don't know what this means re: `Built-in API`

>Jump to document

Your workaround is OK for now

**Comment by zero-plusplus** [comment]
> 1. Is vscode-autohotkey a new extension but is the same code base as vscode-autohotkey-debug?

I don't know what `same code base` stands for.

> 2. Once vscode-autohotkey is released, then this replaces the extension vscode-autohotkey-debug meaning uninstall vscode-autohotkey-debug and install vscode-autohotkey?

No, VSCode can incorporate another extension with a feature called [Extension Packs](https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup). This means that when you install `vscode-autohotkey`, `vscode-autohotkey-debug` is also installed with it.

The vscode-autohotkey-debug was created for the purpose of early release and to work with extensions created by someone else, so it won't go away.

> You mean alrady implemented by slevesque.vscode-autohotkey and dudelmoser.vscode-autohotkey2?

Syntax highlighting is written by me from scratch.

There are two reasons to rewrite it.

1. Since definition files are not programs, they are cumbersome and difficult to  change because they need to be copied and pasted each time the same rules exist, such as variable names and function names. Therefore, I can solve this problem by creating definition files using TypeScript

2. I know the specifications of the definition files better than I did when they were created so I can create better definition files

I am looking at long term maintenance. Therefore, this is a time-consuming but necessary task.

> Intellisense of the Built-in API

Built-in API are things like A_Clipboard and SendInput

> Your workaround is OK for now

I'm glad to hear that.

Note that with v2, can't open the directive's documentation properly.
This is because `getCurrentWord` can't get the `#`.

In v1, there is a redirect so it will automatically move to the document even if the `#` is missing.

**Comment by SAbboushi** [comment]
Good explanations - thank you.

> Syntax highlighting is written by me from scratch.

Excellent!

**Comment by mark-wiemer** [comment]
For opening help for a specific page, see also https://github.com/vscode-autohotkey/ahkpp/issues/78
