### ISSUE TITLE
Are you interested to maintaining autohotkey-plus?

### ISSUE THREAD

**Issue by cweijan** [zero-plusplus/vscode-autohotkey-debug#72]
Hi, At present, my autohotkey script has satisfied my daily work, so I no longer need to use [autohotkey-plus](https://github.com/AutoHotkey-Plus/vscode-autohotkey) extension, I will stop its development, are you interested in maintaining the extension?

**Comment by cweijan** [comment]
When I migrated to vscode, there was only one ahk extension [vscode-autohotkey](https://github.com/stef-levesque/vscode-autohotkey), so I developed ahk-plus based on it. Now it meets my needs and I will end its life, but now there are many users, which makes me feel Trouble, so i want to leave it to you

**Comment by zero-plusplus** [comment]
A very nice offer, but I are working on a similar project and cannot maintain it.

This project will be early released by this year with only minimal functionality implemented.
The difference with the existing extensions is that they support all AutoHotkey versions.

In the future I will implement JavaScript level development support.

**Comment by cweijan** [comment]
Ok.
