### ISSUE TITLE
I cannot apply labels to issues...

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#8]
Do you need to change access writes for me to apply a label to an issue? e.g. "enhancement" or "question"?  Or do you prefer to manage assignment of labels to issues?

**Comment by zero-plusplus** [comment]
I can label it. Is this because it is the owner?

If you don't know how to simply label it, there should be a `Labels` item on the right side of this screen (bottom if the browser is narrow).
You should be able to find what you want by clicking the gear icon there.

**Comment by SAbboushi** [comment]
> I can label it. Is this because it is the owner?

I think so.
 
> If you don't know how to simply label it, there should be a `Labels` item on the right side of this screen (bottom if the browser is narrow).
> You should be able to find what you want by clicking the gear icon there.

![image](https://user-images.githubusercontent.com/1964198/84078057-debb5500-a99d-11ea-9876-3ffb4afc7038.png)


I think according to [this](https://help.github.com/en/github/managing-your-work-on-github/about-labels), only those with write access can apply labels:
"Anyone with read access to a repository can view and search the repository’s labels. To create, edit, apply, or delete a label, you must have write access to the repository."

**Comment by zero-plusplus** [comment]
I'm sorry, I didn't know such specifications.
Why is Github so limiting? I have difficulty understanding.

Forget what I said in #5.
