### ISSUE TITLE
Add a way to get variables that exist on a different call stack in breakpoint, etc.

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#81]
For example, if can get the caller's `A_ThisFunc`, you can break the script only when it is called by a specific function.

If can get the `A_Index` of the caller, can check the number of loops when the if statement branches (for example, branching on error). This is useful when testing a function that automates keystrokes (If want to check whether the function can withstand continuous execution, I need to know the number of times it loops when it fails).

There may be other ways to use it, depending on ideas.

In order to implement this, there is a proposal to extend the `VariableName`.
For now, I'm thinking of a way to specify it like `VariableName:N`, where N is the offset from the top of the call stack.

**Comment by zero-plusplus** [comment]
I close this issue because my original goal can be solved with the `{callstack}` meta-variable, which is implemented #150.

`{callstack}` can retrieve the name, file path, line number, etc. displayed in the current callstack view.
This allows to break only when called by a specific function.

The following is an example of breaking only when called from the Auto-Exec section.
```ahk
{callstack[2].name} ~= "^Auto-execute thread"
```

**Comment by SAbboushi** [comment]
Looks nice
