### ISSUE TITLE
Option to disable debug object "enumerating"

### ISSUE THREAD

**Issue by thegamerx1** [zero-plusplus/vscode-autohotkey-debug#89]
im trying to look at the value of a object with an id but i get this huge list of numbers for a object that only has 2 keys
![image](https://user-images.githubusercontent.com/34986564/107246549-a38f8b00-6a30-11eb-8cb0-684e79b1f979.png)

**Comment by zero-plusplus** [comment]
I forgot to fix this in the previous version... Thank you for the report!

I'm planning to release a new version in the next few days as fixing bugs is a top priority task, but more time may be needed for various reasons.

**Comment by zero-plusplus** [comment]
I'm sorry, but I may have to postpone the release of the new version for various reasons.

**Comment by zero-plusplus** [comment]
Thank you for your patience. I have released [1.6.7](https://marketplace.visualstudio.com/items?itemName=zero-plusplus.vscode-autohotkey-debug) which fixes this issue.
