### ISSUE TITLE
Object properties in Side Bar>Variables pane show "<error>" but displays the values in Debug Console

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#91]
```
; Example: Pass a VARIANT ByRef to a COM method.
var := ComVar.new()
var[] := "in value"

MsgBox var[]

; ComVar: An object which can be used to pass a value ByRef.
;   this[] retrieves the value.
;   this[] := Val sets the value.
;   this.ref retrieves a ByRef object for passing to a COM method.
class ComVar {
    __new(Type := 0xC) {
        ; Allocate memory for the typed variable.
        ; The largest supported type is VT_VARIANT on x64 (24 bytes).
        this.var := BufferAlloc(24, 0)
        ; Create an object which can be used to pass the variable ByRef.
        this.ref := ComObject(0x4000|Type, this.var.ptr + (Type=0xC ? 0 : 8))
    }
    __item {
        get => this.ref[]
        set => this.ref[] := value
    }
}
```
![image](https://user-images.githubusercontent.com/1964198/109427171-bc97b600-79b6-11eb-9e7a-9f98185020cf.png)
![image](https://user-images.githubusercontent.com/1964198/109427563-9a9f3300-79b8-11eb-8e40-6386f1801718.png)

**Comment by SAbboushi** [comment]
After posting the issue, I'm thinking that maybe I read something about this (maybe by helgef or lexikos).  I consider this a low priority issue to examine.

**Comment by zero-plusplus** [comment]
The `"<error>"` that will be set if the value cannot be retrieved will be set by the AutoHotkey debugger. So it seems to be a specification of the AutoHotkey debugger.
However, there seems to be some workarounds as this issue does not occur in the watch expression, the debug console, or even in SciTE4AutoHotkey.

One of the workarounds is to use the method of getting variables found in workaround #51.

I can fix this issue by changing the way get variables in the variables view to above method.
There is probably not much work to do to fix this, so I will be able to release a fixed version soon.

If there is a delay, I will report it here.

**Comment by SAbboushi** [comment]
Thanks for the update.

**Comment by zero-plusplus** [comment]
I don't know the conditions under which this issue occurs, but I can confirm that the value of `instance.base.property` in [demo.ahk2](https://github.com/zero-plusplus/vscode-autohotkey-debug/blob/master/demo/demo.ahk2#L60) becomes `<error>`.
This fix solves the issue in two patterns: your example and the example above.

Since v2 is still under development, I will not investigate further.

I will release a fixed version as early as tomorrow.

**Comment by zero-plusplus** [comment]
It seems that not all patterns can be solved with this fix.
For example, if you store `var.var.base` in your example in an appropriate variable and check that variable, you will still see `<error>`.

I tried to find a solution to the above issue, but could not find one. There doesn't seem to be anything more I can do.

**Comment by SAbboushi** [comment]
ok thanks

**Comment by zero-plusplus** [comment]
I found a workaround for this issue.

First of all, as a prerequisite, it should be known that the debugger is provided with a special name, `<base>`, to distinguish base objects from just user-defined base fields.

If a dynamic property is tried to be retrieved without this special name, it is likely that `<error>` will be retrieved.

So to workaround this, rewrite the above `var.var.base` as `var.var.<base>` and access the debugger.
